### ISSUE TITLE
Failure while upgrading to 4.10.0 due to security Protected resource metadata

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-security#2054]
### Issue description

Original posted:
https://discord.com/channels/1121511613250412714/1431283080387235892

Hello all, I'm seeing the following test failure when I upgrade to 4.10.0. The test is annotated with @MicronautLambdaTest, any ideas what may be causing it. The tests passes if I revert to 4.9.4.
```

MyTest > initializationError FAILED
    io.micronaut.context.exceptions.BeanInstantiationException at DefaultBeanContext.java:2032
        Caused by: io.micronaut.context.exceptions.BeanInstantiationException at AbstractInitializableBeanDefinitionAndReference.java:131
            Caused by: java.lang.NoClassDefFoundError at null:-1
                Caused by: java.lang.ClassNotFoundException at BuiltinClassLoader.java:641
```

```
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.micronaut.security.oauth2.metadata.ResourceMetadataWwwAuthenticateChallengeProvider] could not be loaded: Failed to initialize the bean [class io.micronaut.security.oauth2.metadata.ResourceMetadataWwwAuthenticateChallengeProvider]: io/micronaut/http/server/util/HttpHostResolver

Caused by: java.lang.ClassNotFoundException: io.micronaut.http.server.util.HttpHostResolver
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
    ... 11 more


```
I fixed this by setting the following property:

micronaut.security.oauth2.protected-resource-metadata.enabled=false
https://micronaut-projects.github.io/micronaut-security/snapshot/guide/#protectedResourceMetadata
